# Generated by Django 3.2.7 on 2021-11-02 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_card',
            name='products',
            field=models.ManyToManyField(related_name='shopping_cards', to='product.Product', verbose_name='Products in shopping card'),
        ),
        migrations.CreateModel(
            name='ItemInShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('productOfShoppingCard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productsOfShoppingCard', to='product.shopping_card', verbose_name='product')),
            ],
            options={
                'verbose_name': 'ShoppingCardItem',
                'verbose_name_plural': 'ShoppingCardItems',
            },
        ),
    ]
