# Generated by Django 3.2.7 on 2021-11-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_iteminshoppingcart_userofshoppingcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminshoppingcart',
            name='productOfShoppingCard',
        ),
    ]
