# Generated by Django 3.2.7 on 2021-11-02 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_iteminshoppingcart_productofshoppingcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminshoppingcart',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='prd', to='product.product', verbose_name='Product'),
            preserve_default=False,
        ),
    ]
