# Generated by Django 3.2.7 on 2021-11-02 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0011_alter_iteminshoppingcart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminshoppingcart',
            name='userOfShoppingCard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usersOfShoppingCard', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
