# Generated by Django 3.2.7 on 2021-11-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_iteminshoppingcart_userofshoppingcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminshoppingcart',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
