# Generated by Django 3.2.7 on 2021-11-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_shipping_info_payment'),
        ('product', '0017_alter_shopping_card_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_card',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipaddress', to='order.shipping_info', verbose_name='Shipping Address'),
        ),
    ]
