# Generated by Django 3.2.7 on 2021-11-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20211120_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
    ]
