# Generated by Django 3.2.7 on 2021-11-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
