# Generated by Django 3.2.7 on 2021-11-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping_info',
            name='is_main',
        ),
        migrations.AddField(
            model_name='shipping_info',
            name='payment',
            field=models.IntegerField(default=1, verbose_name='Payment'),
        ),
    ]
