# Generated by Django 3.2.7 on 2021-11-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211114_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping_info',
            name='payment',
        ),
        migrations.AddField(
            model_name='shipping_info',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is Main?'),
        ),
    ]
