# Generated by Django 3.2.7 on 2021-11-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20211114_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_info',
            name='payment',
            field=models.IntegerField(default=1, verbose_name='Payment'),
        ),
    ]
